version: '3.7'

services:
  php_apache:
    image: scto-php:7.4
    volumes:
      - ./public/:/var/www/html/
    ports:
      - 443:443
      - 80:80
    networks:
      - tp_backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1225:1025
      - 8025:8025

networks:
  tp_backend:
    external: true
