version: '3.7'

services:
  php_apache:
    image: scto-php:8.0
    container_name: tp_api_v2
    volumes:
      - ./src/:/var/www/html/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
    ports:
      - 443:443
      - 80:80
    env_file:
      - ./src/.env
    networks:
      - tp_backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1225:1025
      - 8025:8025

networks:
  tp_backend:
    external: true
