version: '3.7'

services:
  php_apache:
    image: scto-php:7.4
    volumes:
      - ./public/:/var/www/html/
    ports:
      - 443:443
      - 80:80
    networks:
      - tp_backend

networks:
  tp_backend:
    external: true
