services:
  php_apache:
    image: scto-php:8.0
    container_name: tp_api_v2
    volumes:
      - ./src/:/var/www/html/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
    ports:
      - 4443:443
      - 1080:80
    env_file:
      - ./src/.env
    networks:
      - tp_backend

networks:
  tp_backend:
    external: true
