openapi: 3.0.3

info:
  version: 0.1.0
  title: Transcribathon Platform API v2
  description: This is the documentation of the Transcribathon API v2.
                For authorization you can use the the bearer token you are provided with.
  contact:
    email: schmucker@factsandfiles.com
  license:
    name: European Union Public License 1.2
    url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

externalDocs:
  url: https://transcribathon.eu
  description: More about Transcribathon

servers:
  - url: https://api.transcribathon.eu.local/api
    description: local dockerized development server
  - url: https://api.transcribathon.local/api
    description: development server within the VPN

security:
  - bearerAuth: []

tags:
  - name: htrdata
    description: Operations for HTR data

paths:
  /htrdata:
    get:
      tags:
        - htrdata
      summary: Get all stored HTR data entries
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/responses/BasicSuccessResponse'
                  - properties:
                      data:
                        type: array
                        description: HTR data entry objects as array
                        items:
                          $ref: '#/components/schemas/HtrDataResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/responses/401ErrorResponse'
    post:
      tags:
        - htrdata
      summary: Store a new HTR data entry
      requestBody:
        description: Data to be stored
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtrDataResponse'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    BasicSuccessResponse:
      type: object
      description: The success response
      properties:
        data:
          type: ['null', string, object]
          description: The requested data, type depending on subschema
        message:
          type: string
          description: An informational message about the response
          example: Data fetched
        success:
          type: boolean
          description: The outcome of the response
          example: true

    BasicErrorResponse:
      type: object
      description: The error response
      properties:
        data:
          type: string
          description: An optional information about the error
        message:
          type: string
          description: An error message
        success:
          type: boolean
          description: The outcome of the response
          example: false

    401ErrorResponse:
      allOf:
        - $ref: '#/components/responses/BasicErrorResponse'
        - properties:
            data:
              nullable: true
              example: null
            message:
              example: Unauthenticated

  schemas:
    HtrDataResponse:
      type: object
      description: The data object of a single entry
      properties:
        created_at:
          type: string
          description: Time of creation
          example: '2022-02-23T09:57:03.000000Z'
        updated_at:
          type: string
          description: Time of last update
          example: '2022-02-23T09:57:03.000000Z'
        data:
          type: string
          description: Requested data
          example: '<?xml version="1.0" encoding="UTF-8"?>'
        data_type:
          type: string
          description: Current type/format of the data (json|xml)
          example: xml
        htr_id:
          type: integer
          description: ID of the used HTR model for this data
          example: 35909
        item_id:
          type: integer
          description: ID of the referenced item
          example: 421717
        process_id:
          type: integer
          description: ID of the process from the Transcribus API
          example: 56845
        status:
          type: string
          description: Current status of the data
          example: CREATED



