openapi: 3.0.3

info:
  version: 0.1.0
  title: Transcribathon Platform API v2
  description: This is the documentation of the Transcribathon API v2.
                For authorization you can use the the bearer token you are provided with.
  contact:
    email: schmucker@factsandfiles.com
  license:
    name: European Union Public License 1.2
    url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

externalDocs:
  url: https://transcribathon.eu
  description: More about Transcribathon

servers:
  - url: https://api.fresenia-dev.man.poznan.pl/v2
    description: public development server
  - url: https://api.transcribathon.local/v2
    description: development server within the VPN
  - url: https://api.transcribathon.eu.local/v2
    description: local dockerized development server

security:
  - bearerAuth: []

tags:
  - name: htrdata
    description: Operations for HTR data

paths:
  /htrdata:
    $ref: 'htrdata-path.yaml'
  /htrdata/{item_id}:
    $ref: 'htrdata-item_id-path.yaml'
  /htrdata/byprocessid/{process_id}:
    $ref: 'htrdata-byprocessid-process_id-path.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    $ref: 'responses.yaml'

  schemas:
    HtrDataPostRequestSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataPostRequestSchema'
    HtrDataPutRequestSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataPutRequestSchema'
    HtrDataGetResponseSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataGetResponseSchema'

