openapi: 3.0.3

info:
  version: 0.6.0-beta
  title: Transcribathon Platform API v2
  description: This is the documentation of the Transcribathon API v2 used by [https:transcribathon.eu](https://transcribathon.eu/).<br />
         For authorization you can use the the bearer token you are provided with.
  contact:
    email: schmucker@factsandfiles.com
  license:
    name: European Union Public License 1.2
    url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

externalDocs:
  url: https://github.com/Facts-and-Files/tp-api/releases
  description: Changelog and releases

servers:
  - url: /v2

security:
  - bearerAuth: []

tags:
  - name: htrdata
    description: Operations related to HTR data
  - name: users
    description: Operations related to users data
  - name: items
    description: Operations related to items data (NOT ALL DATA INCLUDED YET)
  - name: stories
    description: Operations related to stories data

paths:
  /htrdata:
    $ref: 'htrdata-path.yaml'
  /htrdata/{HtrDataId}:
    $ref: 'htrdata-htrdataId-path.yaml'

  /items:
    $ref: 'items-path.yaml'
  /items/{ItemId}:
    $ref: 'items-itemId-path.yaml'
  /items/{ItemId}/htrdata:
    $ref: 'items-itemId-htrdata-path.yaml'

  /users/{UserId}/htrdata:
    $ref: 'users-userId-htrdata-path.yaml'

  /stories:
    $ref: 'stories-path.yaml'
  /stories/{StoryId}:
    $ref: 'stories-storyId-path.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    $ref: 'responses.yaml'

  schemas:
    HtrDataPostRequestSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataPostRequestSchema'
    HtrDataPutRequestSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataPutRequestSchema'
    HtrDataGetResponseSchema:
      $ref: 'htrdata-schema.yaml#/HtrDataGetResponseSchema'
    ItemsGetResponseSchema:
      $ref: 'items-schema.yaml#/ItemsGetResponseSchema'
    ItemsPutResponseSchema:
      $ref: 'items-schema.yaml#/ItemsPutRequestSchema'
    StoriesGetResponseSchema:
      $ref: 'stories-schema.yaml#/StoriesGetResponseSchema'

